wandb_version: 1

name:
  desc: null
  value: infer_original_model
audio_length:
  desc: null
  value: 6
batch_size:
  desc: null
  value: 8
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714409414.0
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 64
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 64
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
