wandb_version: 1

name:
  desc: null
  value: finetune_model
num_epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
start_trainable_layers:
  desc: null
  value: 5
end_trainable_layers:
  desc: null
  value: 5
subset_data:
  desc: null
  value: 0.05
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714472509.0
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 64
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 64
      3:
      - 2
      - 16
      - 23
      4: 3.9.19
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
